export const UPDATE_DRINKS = "UPDATE_DRINKS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";


export const UPDATE_OPTIONS = "UPDATE_OPTIONS";
export const UPDATE_CURRENT_OPTION = "UPDATE_CURRENT_OPTION";
