export const UPDATE_DRINKS = "UPDATE_DRINKS";
export const ADD_TO_CHECKOUT = "ADD_TO_CHECKOUT";
export const ADD_MULTIPLE_TO_CHECKOUT = "ADD_MULTIPLE_TO_CHECKOUT";
export const REMOVE_FROM_CHECKOUT = "ADD_TO_CHECKOUT";
export const CLEAR_CHECKOUT = "CLEAR_CHECKOUT";

export const UPDATE_OPTIONS = "UPDATE_OPTIONS";

export const UPDATE_CURRENT_OPTION = "UPDATE_CURRENT_OPTION";